### ISSUE TITLE
Risks assessment

### ISSUE THREAD

**Issue by luiscaceresd** [luiscaceresd/vikings-game#4]
You are going list out all the risks for the project. Don't forget to include github. Then add it into the prototype document.

**Comment by SomePerson985** [comment]
https://docs.google.com/document/d/1Z2DvvIq2rwaLjp9ynqsUcQ-h4Tt9IIe01ZuUMkk-3Rg/edit?usp=sharing

**Comment by SomePerson985** [comment]
@luiscaceresd [RISK ASSESSMENT DOCUMENT](https://docs.google.com/document/d/1_OUYXYYlu2IGQ14cHPzuKcMBQ0He2WNga7leefKZCf8/edit?usp=sharing)

Check this over, if you approve I'll add it to the **main** document

**Comment by luiscaceresd** [comment]
looks good @SomePerson985
